name: Build Amethyst

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile Metal Shader
        run: |
          cd Amethyst-prebuilt-libraries/SDL/SDL3/src/gpu/metal

          # 1. Biên dịch 6 Shader ra 6 file .air chứa mã binary thực sự
          xcrun -sdk iphoneos metal -c -std=ios-metal2.0 -miphoneos-version-min=11.0 -O3 -D COMPILE_FullscreenVert -o FullscreenVert.air Metal_Blit.metal
          xcrun -sdk iphoneos metal -c -std=ios-metal2.0 -miphoneos-version-min=11.0 -O3 -D COMPILE_BlitFrom2D -o BlitFrom2D.air Metal_Blit.metal
          xcrun -sdk iphoneos metal -c -std=ios-metal2.0 -miphoneos-version-min=11.0 -O3 -D COMPILE_BlitFrom2DArray -o BlitFrom2DArray.air Metal_Blit.metal
          xcrun -sdk iphoneos metal -c -std=ios-metal2.0 -miphoneos-version-min=11.0 -O3 -D COMPILE_BlitFrom3D -o BlitFrom3D.air Metal_Blit.metal
          xcrun -sdk iphoneos metal -c -std=ios-metal2.0 -miphoneos-version-min=11.0 -O3 -D COMPILE_BlitFromCube -o BlitFromCube.air Metal_Blit.metal
          xcrun -sdk iphoneos metal -c -std=ios-metal2.0 -miphoneos-version-min=11.0 -O3 -D COMPILE_BlitFromCubeArray -o BlitFromCubeArray.air Metal_Blit.metal

          # 2. Gom 6 file .air thành 1 file Metal_Blit.metallib duy nhất
          xcrun -sdk iphoneos metallib FullscreenVert.air BlitFrom2D.air BlitFrom2DArray.air BlitFrom3D.air BlitFromCube.air BlitFromCubeArray.air -o Metal_Blit.metallib

          # 3. Dọn dẹp các file .air tạm
          rm -f *.air

          # 4. Kiểm tra dung lượng (sẽ thấy lớn hơn hẳn 96 byte)
          ls -lh Metal_Blit.metallib



      - name: Upload metallib file
        uses: actions/upload-artifact@v4
        with:
          name: metal-shader
          path: Amethyst-prebuilt-libraries/SDL/SDL3/src/gpu/metal/Metal_Blit.metallib
