name: Build Amethyst

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile Metal Shader
        run: |
          cd Amethyst-prebuilt-libraries/SDL/SDL3/src/gpu/metal
          chmod +x compile_shaders.sh
          ./compile_shaders.sh
          ls -lh


      - name: Upload metallib file
        uses: actions/upload-artifact@v4
        with:
          name: metal-shader
          path: Amethyst-prebuilt-libraries/SDL/SDL3/src/gpu/metal/Metal_Blit.metallib
