name: Build Amethyst

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile Metal Shader
        run: |
          cd Amethyst-prebuilt-libraries/SDL/SDL3/src/gpu/metal
          xcrun -sdk iphoneos metal -c -I. Metal_Blit.metal -o Metal_Blit.air
          xcrun -sdk iphoneos metallib Metal_Blit.air -o Metal_Blit.metallib
          ls -lh Metal_Blit.metallib

      - name: Upload metallib file
        uses: actions/upload-artifact@v4
        with:
          name: metal-shader
          path: Amethyst-prebuilt-libraries/SDL/SDL3/src/gpu/metal/Metal_Blit.metallib
